branch-defaults:
  main:
    environment: storefront-api-prod
    group_suffix: null
environment-defaults:
  storefront-api-env:
    branch: null
    repository: null
global:
  application_name: storefront-backend
  branch: null
  default_ec2_keyname: null
  default_platform: Node.js 18 running on 64bit Amazon Linux 2023
  default_region: eu-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
